// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Phantomor",
            "url": "https://github.com/Phantomor"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/user/logout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "清除客户端的 login_token Cookie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块 (User)"
                ],
                "summary": "用户退出登录",
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": \"退出成功\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/chat": {
            "post": {
                "description": "处理基础的聊天请求，返回完整的字符串响应。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI 对话模块 (AI Chat)"
                ],
                "summary": "基础对话 (非流式)",
                "parameters": [
                    {
                        "description": "对话内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, \"data\": \"AI回答的内容...\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"无效的请求参数\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"大脑宕机了: ...\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/chat/stream": {
            "post": {
                "description": "带有 RAG 知识库检索、上下文记忆、MySQL持久化的流式对话接口。使用 Server-Sent Events (SSE) 协议返回数据。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "AI 对话模块 (AI Chat)"
                ],
                "summary": "对话 (SSE 流式)",
                "parameters": [
                    {
                        "description": "包含 SessionID 的对话内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.StreamChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data: {\"content\": \"...\"}\\n\\ndata: [DONE]\\n\\n",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"无效的请求参数\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"流式连接失败...\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/interview/report": {
            "post": {
                "description": "根据候选人历史面试记录、简历和 JD，调用大模型生成结构化的面试评估 JSON 报告。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI 对话模块 (AI Chat)"
                ],
                "summary": "生成面试报告",
                "parameters": [
                    {
                        "description": "报告生成请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": {\"score\": 85, \"strengths\": [...], \"hire_conclusion\": \"Hire\"}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "{\"code\": 400, \"message\": \"参数错误或没有找到面试记录\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "{\"code\": 500, \"message\": \"生成报告失败\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/secops/compliance": {
            "post": {
                "description": "AI 合规顾问专用接口，基于企业零信任规范提供安全编码审查、漏洞修复建议与告警初步研判。具备独立的历史会话隔离 (Redis)。使用 Server-Sent Events (SSE) 协议实时返回审查分析结果。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "ZeroTrust AI 引擎"
                ],
                "summary": "DevSecOps 合规审查对话 (SSE 流式)",
                "parameters": [
                    {
                        "description": "包含 SessionID 的待审计代码片段、架构描述或告警日志",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.StreamChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data: {\\\"content\\\": \\\"...\\\"}\\n\\ndata: [DONE]\\n\\n",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\\\"error\\\": \\\"无效的安全审计请求参数\\\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "{\\\"error\\\": \\\"流式安全连接建立失败...\\\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/secops/threat_hunter": {
            "post": {
                "description": "基于 MCP 协议和 ReAct 引擎，提供自动化安全研判与本地沙箱执行能力",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "ZeroTrust AI 引擎"
                ],
                "summary": "ThreatHunter 核心调度接口",
                "parameters": [
                    {
                        "description": "智能体对话请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ThreatHunterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data: {\"content\": \"...\"}\\n\\ndata: [DONE]\\n\\n",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"参数错误\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"不支持流式或推理中断\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/upload/resume": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "上传简历文件(PDF/Word等)至 MinIO，并异步投递文档解析任务到 Kafka 中转。",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "简历模块 (Resume)"
                ],
                "summary": "异步处理简历上传",
                "parameters": [
                    {
                        "type": "file",
                        "description": "需要上传的简历文件",
                        "name": "resume",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": {\"message\": \"简历上传成功...\", \"object_name\": \"resumes/...\"}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "{\"code\": 400, \"message\": \"请上传简历文件\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "{\"code\": 500, \"message\": \"文件存储失败或任务投递失败\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user/get/login": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "从上下文中获取当前登录用户的 ID 和账号信息（需要登录凭证）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块 (User)"
                ],
                "summary": "获取当前登录用户信息",
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": {\"id\": 1, \"userAccount\": \"xxx\"}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "通过账号密码登录并返回 JWT Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户登录接口",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "账号或密码错误",
                        "schema": {
                            "$ref": "#/definitions/pkg.Response"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "注册新用户，账号至少4位，密码至少6位。密码将在入库前通过 Bcrypt 加密。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块 (User)"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "用户注册参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": \"注册成功\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "{\"code\": 400, \"message\": \"账号已存在或参数校验失败\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "{\"code\": 500, \"message\": \"服务端异常(如加密失败或数据库写入失败)\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ChatRequest": {
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "type": "string",
                    "example": "什么是 GMP 模型？"
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "required": [
                "userAccount",
                "userPassword"
            ],
            "properties": {
                "userAccount": {
                    "type": "string",
                    "example": "admin"
                },
                "userPassword": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "userAccount": {
                    "type": "string",
                    "example": "admin"
                },
                "userName": {
                    "type": "string",
                    "example": "管理员"
                },
                "userRole": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "dto.RegisterRequest": {
            "type": "object",
            "required": [
                "userAccount",
                "userPassword"
            ],
            "properties": {
                "userAccount": {
                    "type": "string",
                    "minLength": 4,
                    "example": "testuser"
                },
                "userPassword": {
                    "type": "string",
                    "minLength": 6,
                    "example": "123456"
                }
            }
        },
        "dto.ReportRequest": {
            "type": "object",
            "required": [
                "jd",
                "resume",
                "session_id"
            ],
            "properties": {
                "jd": {
                    "type": "string",
                    "example": "需要3年Go开发经验，熟悉GMP模型..."
                },
                "resume": {
                    "type": "string",
                    "example": "熟练掌握Go语言，具有高并发经验..."
                },
                "session_id": {
                    "type": "string",
                    "example": "user_123_session"
                }
            }
        },
        "dto.StreamChatRequest": {
            "type": "object",
            "required": [
                "message",
                "session_id"
            ],
            "properties": {
                "message": {
                    "type": "string",
                    "example": "请解释一下 Go 的垃圾回收机制。"
                },
                "session_id": {
                    "type": "string",
                    "example": "user_123_session"
                }
            }
        },
        "dto.ThreatHunterRequest": {
            "type": "object",
            "required": [
                "message",
                "session_id"
            ],
            "properties": {
                "message": {
                    "type": "string",
                    "example": "帮我查一下这名候选人的背景信息"
                },
                "session_id": {
                    "type": "string",
                    "example": "threat_hunter_123_session"
                }
            }
        },
        "pkg.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "description": "这个字段名或 JSON tag 必须叫 data"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "ZeroTrust Sentinel API",
	Description:      "基于 Go + MCP 协议的企业级零信任安全智能体平台 (AI SecOps)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
